// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// Token on login response needs to be set in metadata on the context for grpc
// calls in order to use chat service the token should be sent using key token
type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Message struct {
	Data                 string   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=From,proto3" json:"From,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=To,proto3" json:"To,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Message) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Message) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type MessageList struct {
	Messages             []*Message `protobuf:"bytes,1,rep,name=Messages,proto3" json:"Messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MessageList) Reset()         { *m = MessageList{} }
func (m *MessageList) String() string { return proto.CompactTextString(m) }
func (*MessageList) ProtoMessage()    {}
func (*MessageList) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{4}
}

func (m *MessageList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageList.Unmarshal(m, b)
}
func (m *MessageList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageList.Marshal(b, m, deterministic)
}
func (m *MessageList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageList.Merge(m, src)
}
func (m *MessageList) XXX_Size() int {
	return xxx_messageInfo_MessageList.Size(m)
}
func (m *MessageList) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageList.DiscardUnknown(m)
}

var xxx_messageInfo_MessageList proto.InternalMessageInfo

func (m *MessageList) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type RoomMessage struct {
	RoomID               string   `protobuf:"bytes,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	Message              *Message `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomMessage) Reset()         { *m = RoomMessage{} }
func (m *RoomMessage) String() string { return proto.CompactTextString(m) }
func (*RoomMessage) ProtoMessage()    {}
func (*RoomMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{5}
}

func (m *RoomMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomMessage.Unmarshal(m, b)
}
func (m *RoomMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomMessage.Marshal(b, m, deterministic)
}
func (m *RoomMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomMessage.Merge(m, src)
}
func (m *RoomMessage) XXX_Size() int {
	return xxx_messageInfo_RoomMessage.Size(m)
}
func (m *RoomMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RoomMessage proto.InternalMessageInfo

func (m *RoomMessage) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *RoomMessage) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type Room struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{6}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type MessageResp struct {
	Data                 string   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageResp) Reset()         { *m = MessageResp{} }
func (m *MessageResp) String() string { return proto.CompactTextString(m) }
func (*MessageResp) ProtoMessage()    {}
func (*MessageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{7}
}

func (m *MessageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResp.Unmarshal(m, b)
}
func (m *MessageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResp.Marshal(b, m, deterministic)
}
func (m *MessageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResp.Merge(m, src)
}
func (m *MessageResp) XXX_Size() int {
	return xxx_messageInfo_MessageResp.Size(m)
}
func (m *MessageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResp.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResp proto.InternalMessageInfo

func (m *MessageResp) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type RegisterRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{8}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *RegisterRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type RegisterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{9}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

type FriendsListReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendsListReq) Reset()         { *m = FriendsListReq{} }
func (m *FriendsListReq) String() string { return proto.CompactTextString(m) }
func (*FriendsListReq) ProtoMessage()    {}
func (*FriendsListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{10}
}

func (m *FriendsListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendsListReq.Unmarshal(m, b)
}
func (m *FriendsListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendsListReq.Marshal(b, m, deterministic)
}
func (m *FriendsListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendsListReq.Merge(m, src)
}
func (m *FriendsListReq) XXX_Size() int {
	return xxx_messageInfo_FriendsListReq.Size(m)
}
func (m *FriendsListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendsListReq.DiscardUnknown(m)
}

var xxx_messageInfo_FriendsListReq proto.InternalMessageInfo

type FriendsList struct {
	Friends              []*Friend `protobuf:"bytes,1,rep,name=Friends,proto3" json:"Friends,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FriendsList) Reset()         { *m = FriendsList{} }
func (m *FriendsList) String() string { return proto.CompactTextString(m) }
func (*FriendsList) ProtoMessage()    {}
func (*FriendsList) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{11}
}

func (m *FriendsList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendsList.Unmarshal(m, b)
}
func (m *FriendsList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendsList.Marshal(b, m, deterministic)
}
func (m *FriendsList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendsList.Merge(m, src)
}
func (m *FriendsList) XXX_Size() int {
	return xxx_messageInfo_FriendsList.Size(m)
}
func (m *FriendsList) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendsList.DiscardUnknown(m)
}

var xxx_messageInfo_FriendsList proto.InternalMessageInfo

func (m *FriendsList) GetFriends() []*Friend {
	if m != nil {
		return m.Friends
	}
	return nil
}

type Friend struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=Status,proto3" json:"Status,omitempty"`
	Online               bool     `protobuf:"varint,6,opt,name=Online,proto3" json:"Online,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Friend) Reset()         { *m = Friend{} }
func (m *Friend) String() string { return proto.CompactTextString(m) }
func (*Friend) ProtoMessage()    {}
func (*Friend) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{12}
}

func (m *Friend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friend.Unmarshal(m, b)
}
func (m *Friend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friend.Marshal(b, m, deterministic)
}
func (m *Friend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friend.Merge(m, src)
}
func (m *Friend) XXX_Size() int {
	return xxx_messageInfo_Friend.Size(m)
}
func (m *Friend) XXX_DiscardUnknown() {
	xxx_messageInfo_Friend.DiscardUnknown(m)
}

var xxx_messageInfo_Friend proto.InternalMessageInfo

func (m *Friend) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Friend) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Friend) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Friend) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Friend) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Friend) GetOnline() bool {
	if m != nil {
		return m.Online
	}
	return false
}

type FriendAddResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendAddResp) Reset()         { *m = FriendAddResp{} }
func (m *FriendAddResp) String() string { return proto.CompactTextString(m) }
func (*FriendAddResp) ProtoMessage()    {}
func (*FriendAddResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{13}
}

func (m *FriendAddResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendAddResp.Unmarshal(m, b)
}
func (m *FriendAddResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendAddResp.Marshal(b, m, deterministic)
}
func (m *FriendAddResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendAddResp.Merge(m, src)
}
func (m *FriendAddResp) XXX_Size() int {
	return xxx_messageInfo_FriendAddResp.Size(m)
}
func (m *FriendAddResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendAddResp.DiscardUnknown(m)
}

var xxx_messageInfo_FriendAddResp proto.InternalMessageInfo

type FriendRemoveResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendRemoveResp) Reset()         { *m = FriendRemoveResp{} }
func (m *FriendRemoveResp) String() string { return proto.CompactTextString(m) }
func (*FriendRemoveResp) ProtoMessage()    {}
func (*FriendRemoveResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{14}
}

func (m *FriendRemoveResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendRemoveResp.Unmarshal(m, b)
}
func (m *FriendRemoveResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendRemoveResp.Marshal(b, m, deterministic)
}
func (m *FriendRemoveResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendRemoveResp.Merge(m, src)
}
func (m *FriendRemoveResp) XXX_Size() int {
	return xxx_messageInfo_FriendRemoveResp.Size(m)
}
func (m *FriendRemoveResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendRemoveResp.DiscardUnknown(m)
}

var xxx_messageInfo_FriendRemoveResp proto.InternalMessageInfo

type FriendRequests struct {
	Friends              []*Friend `protobuf:"bytes,1,rep,name=Friends,proto3" json:"Friends,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FriendRequests) Reset()         { *m = FriendRequests{} }
func (m *FriendRequests) String() string { return proto.CompactTextString(m) }
func (*FriendRequests) ProtoMessage()    {}
func (*FriendRequests) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{15}
}

func (m *FriendRequests) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendRequests.Unmarshal(m, b)
}
func (m *FriendRequests) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendRequests.Marshal(b, m, deterministic)
}
func (m *FriendRequests) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendRequests.Merge(m, src)
}
func (m *FriendRequests) XXX_Size() int {
	return xxx_messageInfo_FriendRequests.Size(m)
}
func (m *FriendRequests) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendRequests.DiscardUnknown(m)
}

var xxx_messageInfo_FriendRequests proto.InternalMessageInfo

func (m *FriendRequests) GetFriends() []*Friend {
	if m != nil {
		return m.Friends
	}
	return nil
}

type FriendStatus struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	Online               bool     `protobuf:"varint,3,opt,name=Online,proto3" json:"Online,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendStatus) Reset()         { *m = FriendStatus{} }
func (m *FriendStatus) String() string { return proto.CompactTextString(m) }
func (*FriendStatus) ProtoMessage()    {}
func (*FriendStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{16}
}

func (m *FriendStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendStatus.Unmarshal(m, b)
}
func (m *FriendStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendStatus.Marshal(b, m, deterministic)
}
func (m *FriendStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendStatus.Merge(m, src)
}
func (m *FriendStatus) XXX_Size() int {
	return xxx_messageInfo_FriendStatus.Size(m)
}
func (m *FriendStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendStatus.DiscardUnknown(m)
}

var xxx_messageInfo_FriendStatus proto.InternalMessageInfo

func (m *FriendStatus) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *FriendStatus) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *FriendStatus) GetOnline() bool {
	if m != nil {
		return m.Online
	}
	return false
}

type StatusUpdate struct {
	Status               string   `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Online               bool     `protobuf:"varint,2,opt,name=Online,proto3" json:"Online,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusUpdate) Reset()         { *m = StatusUpdate{} }
func (m *StatusUpdate) String() string { return proto.CompactTextString(m) }
func (*StatusUpdate) ProtoMessage()    {}
func (*StatusUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{17}
}

func (m *StatusUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusUpdate.Unmarshal(m, b)
}
func (m *StatusUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusUpdate.Marshal(b, m, deterministic)
}
func (m *StatusUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusUpdate.Merge(m, src)
}
func (m *StatusUpdate) XXX_Size() int {
	return xxx_messageInfo_StatusUpdate.Size(m)
}
func (m *StatusUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_StatusUpdate proto.InternalMessageInfo

func (m *StatusUpdate) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *StatusUpdate) GetOnline() bool {
	if m != nil {
		return m.Online
	}
	return false
}

func init() {
	proto.RegisterType((*Empty)(nil), "api.Empty")
	proto.RegisterType((*LoginRequest)(nil), "api.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "api.LoginResponse")
	proto.RegisterType((*Message)(nil), "api.Message")
	proto.RegisterType((*MessageList)(nil), "api.MessageList")
	proto.RegisterType((*RoomMessage)(nil), "api.RoomMessage")
	proto.RegisterType((*Room)(nil), "api.Room")
	proto.RegisterType((*MessageResp)(nil), "api.MessageResp")
	proto.RegisterType((*RegisterRequest)(nil), "api.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "api.RegisterResponse")
	proto.RegisterType((*FriendsListReq)(nil), "api.FriendsListReq")
	proto.RegisterType((*FriendsList)(nil), "api.FriendsList")
	proto.RegisterType((*Friend)(nil), "api.Friend")
	proto.RegisterType((*FriendAddResp)(nil), "api.FriendAddResp")
	proto.RegisterType((*FriendRemoveResp)(nil), "api.FriendRemoveResp")
	proto.RegisterType((*FriendRequests)(nil), "api.FriendRequests")
	proto.RegisterType((*FriendStatus)(nil), "api.FriendStatus")
	proto.RegisterType((*StatusUpdate)(nil), "api.StatusUpdate")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 663 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x5b, 0x6b, 0x13, 0x41,
	0x14, 0xde, 0xdd, 0x5c, 0x9a, 0x9c, 0xa4, 0xb7, 0xd3, 0x5a, 0x42, 0xf0, 0xa1, 0x0e, 0x54, 0x02,
	0x6a, 0x5a, 0xa2, 0x50, 0x7c, 0x11, 0x82, 0x6d, 0xa0, 0xd0, 0xaa, 0x6c, 0x53, 0x04, 0xdf, 0x46,
	0x76, 0x68, 0x17, 0xb3, 0x3b, 0xdb, 0x9d, 0xa9, 0xe2, 0x4f, 0xf1, 0xc1, 0x37, 0x7f, 0xa6, 0x0f,
	0x32, 0xb7, 0xcd, 0xac, 0xb6, 0x45, 0xe8, 0xdb, 0x9c, 0xeb, 0x7c, 0xdf, 0x39, 0x67, 0xce, 0xc0,
	0x5a, 0xc6, 0x84, 0xa0, 0x97, 0x4c, 0x8c, 0x8b, 0x92, 0x4b, 0x8e, 0x0d, 0x5a, 0xa4, 0x64, 0x05,
	0x5a, 0xc7, 0x59, 0x21, 0xbf, 0x93, 0x19, 0xf4, 0x4f, 0xf9, 0x65, 0x9a, 0xc7, 0xec, 0xfa, 0x86,
	0x09, 0x89, 0x43, 0xe8, 0x5c, 0x08, 0x56, 0xe6, 0x34, 0x63, 0x83, 0x70, 0x37, 0x1c, 0x75, 0xe3,
	0x4a, 0x56, 0xb6, 0x0f, 0x54, 0x88, 0x6f, 0xbc, 0x4c, 0x06, 0x91, 0xb1, 0x39, 0x99, 0xec, 0xc1,
	0xaa, 0xcd, 0x23, 0x0a, 0x9e, 0x0b, 0x86, 0xdb, 0xd0, 0x9a, 0xf3, 0x2f, 0x2c, 0xb7, 0x59, 0x8c,
	0x40, 0xa6, 0xb0, 0x72, 0x66, 0xe0, 0x20, 0x42, 0xf3, 0x88, 0x4a, 0x6a, 0xed, 0xfa, 0xac, 0x74,
	0xb3, 0x92, 0x67, 0x36, 0xbb, 0x3e, 0xe3, 0x1a, 0x44, 0x73, 0x3e, 0x68, 0x68, 0x4d, 0x34, 0xe7,
	0xe4, 0x10, 0x7a, 0x36, 0xc5, 0x69, 0x2a, 0x24, 0x8e, 0xa0, 0x63, 0x45, 0x31, 0x08, 0x77, 0x1b,
	0xa3, 0xde, 0xa4, 0x3f, 0xa6, 0x45, 0x3a, 0xb6, 0xca, 0xb8, 0xb2, 0x92, 0x33, 0xe8, 0xc5, 0x9c,
	0x67, 0xee, 0xfe, 0x1d, 0x68, 0x2b, 0xf1, 0xe4, 0xc8, 0x22, 0xb0, 0x12, 0x3e, 0xad, 0x20, 0x6a,
	0x18, 0x7f, 0xe7, 0x73, 0x46, 0xb2, 0x03, 0x4d, 0x15, 0xa1, 0xf0, 0x55, 0x39, 0xa2, 0x93, 0x23,
	0xf2, 0xa4, 0xc2, 0xa7, 0x6a, 0x71, 0x1b, 0x4d, 0xf2, 0x23, 0x84, 0xf5, 0x98, 0x5d, 0xa6, 0x42,
	0xb2, 0xf2, 0x81, 0x85, 0xc7, 0xc7, 0xd0, 0x9d, 0xa5, 0xa5, 0x90, 0xef, 0x54, 0xa0, 0xa9, 0xd2,
	0x52, 0xa1, 0x22, 0x4f, 0xa9, 0x35, 0x36, 0x4d, 0xa4, 0x93, 0x55, 0x87, 0x8e, 0x33, 0x9a, 0x2e,
	0x06, 0x2d, 0xd3, 0x21, 0x2d, 0x10, 0x84, 0x8d, 0x25, 0x34, 0xd3, 0x4b, 0xb2, 0x01, 0x6b, 0xb3,
	0x32, 0x65, 0x79, 0x22, 0x54, 0xc9, 0x63, 0x76, 0x4d, 0x5e, 0x41, 0xcf, 0xd3, 0xe0, 0x1e, 0xac,
	0x58, 0xd1, 0xf6, 0xa0, 0xa7, 0x6b, 0x66, 0x74, 0xb1, 0xb3, 0x91, 0x5f, 0x21, 0xb4, 0xcd, 0xf9,
	0x5e, 0xba, 0x15, 0xb0, 0xc8, 0x03, 0xf6, 0x00, 0xa2, 0x3b, 0xd0, 0x3e, 0x97, 0x54, 0xde, 0x08,
	0xcb, 0xd4, 0x4a, 0x4a, 0xff, 0x3e, 0x5f, 0xa4, 0x39, 0x1b, 0xb4, 0x77, 0xc3, 0x51, 0x27, 0xb6,
	0x12, 0x59, 0x87, 0x55, 0x83, 0x72, 0x9a, 0x24, 0xaa, 0x06, 0xaa, 0x26, 0x96, 0x0a, 0xcb, 0xf8,
	0x57, 0xdd, 0x57, 0x72, 0xe8, 0x6a, 0x62, 0x1b, 0x28, 0xfe, 0xb7, 0x08, 0x9f, 0xa0, 0x6f, 0x8e,
	0x16, 0xc5, 0x7d, 0x95, 0x58, 0x22, 0x8f, 0xee, 0x40, 0xde, 0xa8, 0x21, 0x7f, 0x03, 0x7d, 0xe3,
	0x71, 0x51, 0x24, 0x54, 0xfa, 0xf1, 0xe1, 0x1d, 0xf1, 0x91, 0x1f, 0x3f, 0xf9, 0x1d, 0x42, 0xf3,
	0xed, 0x15, 0x95, 0xb8, 0x0f, 0xbd, 0x73, 0x96, 0x27, 0xee, 0xad, 0xd4, 0x9e, 0xc0, 0x70, 0xa3,
	0xf6, 0x20, 0x54, 0x31, 0x02, 0xdc, 0x87, 0xbe, 0x7b, 0x68, 0x1f, 0x53, 0x79, 0x85, 0x3e, 0xf7,
	0x7a, 0x80, 0x1a, 0x18, 0x12, 0xe0, 0x6b, 0xd8, 0xf4, 0x6e, 0x98, 0x73, 0xfd, 0x96, 0x8c, 0xa3,
	0xf7, 0x4a, 0x6f, 0xbd, 0xeb, 0x05, 0xf4, 0x3d, 0x17, 0x81, 0xdd, 0x2a, 0xea, 0xd6, 0x9b, 0xbc,
	0x0d, 0x81, 0xa0, 0xed, 0x7a, 0xf5, 0x0d, 0x6b, 0xa4, 0x48, 0x70, 0x10, 0x4e, 0x7e, 0x46, 0x55,
	0x0b, 0x71, 0x0c, 0x8d, 0xe9, 0x62, 0x81, 0x5b, 0x1e, 0x0f, 0x37, 0xfd, 0xf6, 0x16, 0x4f, 0xa9,
	0x6f, 0x69, 0x4c, 0x93, 0xa4, 0xce, 0x1b, 0x3d, 0xc1, 0xcd, 0x52, 0x80, 0x63, 0x68, 0x9b, 0x39,
	0xaa, 0x3b, 0x3f, 0xf2, 0xa7, 0x65, 0x39, 0x67, 0x8a, 0x6e, 0xa7, 0x9a, 0x31, 0x1f, 0xff, 0x56,
	0x2d, 0xc0, 0x38, 0x90, 0x00, 0x9f, 0xb9, 0x9e, 0xd7, 0x9c, 0x37, 0x3d, 0x67, 0x63, 0x56, 0x8c,
	0xf1, 0x39, 0x74, 0xcf, 0x99, 0xb4, 0xfe, 0xc6, 0xc7, 0x1f, 0xa0, 0xa1, 0x97, 0x82, 0x04, 0x13,
	0x01, 0xcd, 0xe9, 0x8d, 0xbc, 0xc2, 0x03, 0x68, 0xe9, 0x65, 0x6f, 0x23, 0xfc, 0x0f, 0xc4, 0x72,
	0xae, 0xfd, 0x05, 0xba, 0xdb, 0x1d, 0xb7, 0x55, 0x70, 0xdb, 0xb4, 0xab, 0xbe, 0xff, 0x2c, 0xfd,
	0x7f, 0x56, 0x4f, 0xf0, 0xb9, 0xad, 0xbf, 0xad, 0x97, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4c,
	0xfa, 0x93, 0x6f, 0xc8, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatClient interface {
	SendMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*MessageResp, error)
	MessagesWith(ctx context.Context, in *Friend, opts ...grpc.CallOption) (*MessageList, error)
	SendMessageToRoom(ctx context.Context, in *RoomMessage, opts ...grpc.CallOption) (*MessageResp, error)
	RoomMessages(ctx context.Context, in *Room, opts ...grpc.CallOption) (*MessageList, error)
	Messages(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Chat_MessagesClient, error)
}

type chatClient struct {
	cc *grpc.ClientConn
}

func NewChatClient(cc *grpc.ClientConn) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) SendMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*MessageResp, error) {
	out := new(MessageResp)
	err := c.cc.Invoke(ctx, "/api.Chat/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) MessagesWith(ctx context.Context, in *Friend, opts ...grpc.CallOption) (*MessageList, error) {
	out := new(MessageList)
	err := c.cc.Invoke(ctx, "/api.Chat/MessagesWith", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) SendMessageToRoom(ctx context.Context, in *RoomMessage, opts ...grpc.CallOption) (*MessageResp, error) {
	out := new(MessageResp)
	err := c.cc.Invoke(ctx, "/api.Chat/SendMessageToRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) RoomMessages(ctx context.Context, in *Room, opts ...grpc.CallOption) (*MessageList, error) {
	out := new(MessageList)
	err := c.cc.Invoke(ctx, "/api.Chat/RoomMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) Messages(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Chat_MessagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Chat_serviceDesc.Streams[0], "/api.Chat/Messages", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatMessagesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Chat_MessagesClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type chatMessagesClient struct {
	grpc.ClientStream
}

func (x *chatMessagesClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatServer is the server API for Chat service.
type ChatServer interface {
	SendMessage(context.Context, *Message) (*MessageResp, error)
	MessagesWith(context.Context, *Friend) (*MessageList, error)
	SendMessageToRoom(context.Context, *RoomMessage) (*MessageResp, error)
	RoomMessages(context.Context, *Room) (*MessageList, error)
	Messages(*Empty, Chat_MessagesServer) error
}

// UnimplementedChatServer can be embedded to have forward compatible implementations.
type UnimplementedChatServer struct {
}

func (*UnimplementedChatServer) SendMessage(ctx context.Context, req *Message) (*MessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (*UnimplementedChatServer) MessagesWith(ctx context.Context, req *Friend) (*MessageList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MessagesWith not implemented")
}
func (*UnimplementedChatServer) SendMessageToRoom(ctx context.Context, req *RoomMessage) (*MessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessageToRoom not implemented")
}
func (*UnimplementedChatServer) RoomMessages(ctx context.Context, req *Room) (*MessageList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RoomMessages not implemented")
}
func (*UnimplementedChatServer) Messages(req *Empty, srv Chat_MessagesServer) error {
	return status.Errorf(codes.Unimplemented, "method Messages not implemented")
}

func RegisterChatServer(s *grpc.Server, srv ChatServer) {
	s.RegisterService(&_Chat_serviceDesc, srv)
}

func _Chat_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Chat/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).SendMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_MessagesWith_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Friend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).MessagesWith(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Chat/MessagesWith",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).MessagesWith(ctx, req.(*Friend))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_SendMessageToRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).SendMessageToRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Chat/SendMessageToRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).SendMessageToRoom(ctx, req.(*RoomMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_RoomMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Room)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).RoomMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Chat/RoomMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).RoomMessages(ctx, req.(*Room))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_Messages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServer).Messages(m, &chatMessagesServer{stream})
}

type Chat_MessagesServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type chatMessagesServer struct {
	grpc.ServerStream
}

func (x *chatMessagesServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

var _Chat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _Chat_SendMessage_Handler,
		},
		{
			MethodName: "MessagesWith",
			Handler:    _Chat_MessagesWith_Handler,
		},
		{
			MethodName: "SendMessageToRoom",
			Handler:    _Chat_SendMessageToRoom_Handler,
		},
		{
			MethodName: "RoomMessages",
			Handler:    _Chat_RoomMessages_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Messages",
			Handler:       _Chat_Messages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "messages.proto",
}

// FriendsClient is the client API for Friends service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FriendsClient interface {
	All(ctx context.Context, in *FriendsListReq, opts ...grpc.CallOption) (*FriendsList, error)
	Add(ctx context.Context, in *Friend, opts ...grpc.CallOption) (*FriendAddResp, error)
	Remove(ctx context.Context, in *Friend, opts ...grpc.CallOption) (*FriendRemoveResp, error)
	Requests(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FriendRequests, error)
	Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Friends_StatusClient, error)
	SetStatus(ctx context.Context, in *StatusUpdate, opts ...grpc.CallOption) (*Empty, error)
}

type friendsClient struct {
	cc *grpc.ClientConn
}

func NewFriendsClient(cc *grpc.ClientConn) FriendsClient {
	return &friendsClient{cc}
}

func (c *friendsClient) All(ctx context.Context, in *FriendsListReq, opts ...grpc.CallOption) (*FriendsList, error) {
	out := new(FriendsList)
	err := c.cc.Invoke(ctx, "/api.Friends/All", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsClient) Add(ctx context.Context, in *Friend, opts ...grpc.CallOption) (*FriendAddResp, error) {
	out := new(FriendAddResp)
	err := c.cc.Invoke(ctx, "/api.Friends/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsClient) Remove(ctx context.Context, in *Friend, opts ...grpc.CallOption) (*FriendRemoveResp, error) {
	out := new(FriendRemoveResp)
	err := c.cc.Invoke(ctx, "/api.Friends/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsClient) Requests(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FriendRequests, error) {
	out := new(FriendRequests)
	err := c.cc.Invoke(ctx, "/api.Friends/Requests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsClient) Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Friends_StatusClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Friends_serviceDesc.Streams[0], "/api.Friends/Status", opts...)
	if err != nil {
		return nil, err
	}
	x := &friendsStatusClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Friends_StatusClient interface {
	Recv() (*FriendStatus, error)
	grpc.ClientStream
}

type friendsStatusClient struct {
	grpc.ClientStream
}

func (x *friendsStatusClient) Recv() (*FriendStatus, error) {
	m := new(FriendStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *friendsClient) SetStatus(ctx context.Context, in *StatusUpdate, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.Friends/SetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FriendsServer is the server API for Friends service.
type FriendsServer interface {
	All(context.Context, *FriendsListReq) (*FriendsList, error)
	Add(context.Context, *Friend) (*FriendAddResp, error)
	Remove(context.Context, *Friend) (*FriendRemoveResp, error)
	Requests(context.Context, *Empty) (*FriendRequests, error)
	Status(*Empty, Friends_StatusServer) error
	SetStatus(context.Context, *StatusUpdate) (*Empty, error)
}

// UnimplementedFriendsServer can be embedded to have forward compatible implementations.
type UnimplementedFriendsServer struct {
}

func (*UnimplementedFriendsServer) All(ctx context.Context, req *FriendsListReq) (*FriendsList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method All not implemented")
}
func (*UnimplementedFriendsServer) Add(ctx context.Context, req *Friend) (*FriendAddResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedFriendsServer) Remove(ctx context.Context, req *Friend) (*FriendRemoveResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}
func (*UnimplementedFriendsServer) Requests(ctx context.Context, req *Empty) (*FriendRequests, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Requests not implemented")
}
func (*UnimplementedFriendsServer) Status(req *Empty, srv Friends_StatusServer) error {
	return status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (*UnimplementedFriendsServer) SetStatus(ctx context.Context, req *StatusUpdate) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetStatus not implemented")
}

func RegisterFriendsServer(s *grpc.Server, srv FriendsServer) {
	s.RegisterService(&_Friends_serviceDesc, srv)
}

func _Friends_All_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendsListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServer).All(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Friends/All",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServer).All(ctx, req.(*FriendsListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friends_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Friend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Friends/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServer).Add(ctx, req.(*Friend))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friends_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Friend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Friends/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServer).Remove(ctx, req.(*Friend))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friends_Requests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServer).Requests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Friends/Requests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServer).Requests(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friends_Status_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FriendsServer).Status(m, &friendsStatusServer{stream})
}

type Friends_StatusServer interface {
	Send(*FriendStatus) error
	grpc.ServerStream
}

type friendsStatusServer struct {
	grpc.ServerStream
}

func (x *friendsStatusServer) Send(m *FriendStatus) error {
	return x.ServerStream.SendMsg(m)
}

func _Friends_SetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServer).SetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Friends/SetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServer).SetStatus(ctx, req.(*StatusUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

var _Friends_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Friends",
	HandlerType: (*FriendsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "All",
			Handler:    _Friends_All_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _Friends_Add_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Friends_Remove_Handler,
		},
		{
			MethodName: "Requests",
			Handler:    _Friends_Requests_Handler,
		},
		{
			MethodName: "SetStatus",
			Handler:    _Friends_SetStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Status",
			Handler:       _Friends_Status_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "messages.proto",
}

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/api.Auth/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/api.Auth/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAuthServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Auth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Auth/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Auth_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Auth_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messages.proto",
}
